cursor #eda792
cursor_text_color #1e1e00

foreground            #f0f0f0
background            #09070d
selection_foreground  #1e1e00
selection_background  #49ccd2
url_color             #eda792

color0   #130f1a
color1   #ff7672
color2   #8ded76
color3   #ffe572
color4   #e19179
color5   #8c645b
color6   #eda792
color7   #f8ece9
color8   #453e3d
color9   #ffa29f
color10  #b7ffa5
color11  #ffeea5
color12  #ffbeab
color13  #ffcaba
color14  #ffddd2
color15  #fff9f8
