-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(eda792)",
			inactive_border = "rgb(d9bcb8)",
		},
	},
	group = {
		col = {
			border_active = "rgb(eda792)",
			border_inactive = "rgb(d9bcb8)",
			border_locked_active = "rgb(f38ba8)",
			border_locked_inactive = "rgb(d9bcb8)",
		},
		groupbar = {
			col = {
				active = "rgb(eda792)",
				inactive = "rgb(d9bcb8)",
				locked_active = "rgb(f38ba8)",
				locked_inactive = "rgb(d9bcb8)",
			},
		},
	},
})
